### ISSUE TITLE
Integration test failures in pipeline

### ISSUE THREAD

**Issue by brittshook** [My-Budget-Buddy/Budget-Buddy-BudgetService#51]
Failures: 
[ERROR]   BucketControllerIntegrationTest.testGetAllBuckets:50 JSON path "$.length()" expected:<6> but was:<8>
[ERROR]   BudgetControllerIntegrationTest.testFindAllBudgets:59 JSON path "$.length()" expected:<6> but was:<8>
[ERROR]   MonthlySummaryControllerIntegrationTest.testFindAllSummarys:45 JSON path "$.length()" expected:<3> but was:<4>

**Comment by AndyZheng430** [comment]
The error is appearing because those integration tests check for the length of array of objects retrieved. It seems like a mismatch of lengths of expected and actual.
